In [1]:
import numpy as np

#### **배열생성**
    * 리스트로 배열 만들기

In [2]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1)) 
print(a1.shape) # 5개의 원소 1차원 배열임을 확인
print(a1[0],a1[1],a1[2],a1[3],a1[4])

# 값 수정하기
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


<font color = "blue">***2차원형태 배열 생성***</font>

In [3]:
array_2D = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(array_2D)

print("=" * 33)

print("생성된 이차원 어레이의 구조", array_2D.shape)
print("이차원 어레이에 접근 예시 _ : array_2D[0, 0], array_2D[1][0], array_2D[2, 2] = ", array_2D[0, 0], array_2D[1][0], array_2D[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
생성된 이차원 어레이의 구조 (3, 3)
이차원 어레이에 접근 예시 _ : array_2D[0, 0], array_2D[1][0], array_2D[2, 2] =  1 4 9


---

<font color = "blue"> ***3차원 어레이 개념과 생성생성***</font>

<img src="https://kr.mathworks.com/help/matlab/math/nddemo_02_ko_KR.gif" alt="image info" />

In [4]:
# 이차원형태 배열 생성
array_3D = np.array([[ [1,2,3], [4,5,6], [7,8,9] ],
                   [ [1,2,3], [4,5,6], [7,8,9] ],
                   [ [1,2,3], [4,5,6], [7,8,9] ]])
print(array_3D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [5]:
print(array_3D.shape)

(3, 3, 3)


<font color = "blue">***배열 생성과 초기화***</font>

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full((3,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

In [9]:
# 단위행렬 지정
# : 정사각행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# 삼각행렬 생성
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

***empty()***

    - 초기화가 없어서 배열 생성비용이 저렴하고 빠르다.
    - 단, 초기화되지 않아 기존 메모리 위치에 존재하는 값이 자동으로 설정됨을 주의

In [11]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

***_like() : : 지정한 배열과 같은 shape의 행렬 생성***

    - np.zeros_like()
    - np.ones_like()
    - np.full_like()
    - np.empty_like()    

In [20]:
print(array_3D)

# 0를 통해 수 채움
print("="*10, "copied with np.zeros")
print(np.zeros_like(array_3D))

# 1를 통해 수 채움
print("="*10, "copied with np.ones")
print(np.ones_like(array_3D))

# 지정 값을 통해 수 채움
print("="*10, "copied with np.full")
print(np.full_like(array_3D, fill_value = 3.14))

# 지정 값 없이 값 채움 : 
# 특징_1 기존에 메모리에 저장되어 있던 값을 임의로 활용
# 특징_2 메모리 할당이 적음으로 가성비가 높음

print("="*10, "copied with np.empty")
print(np.empty_like(array_3D))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
========== copied with np.zeros
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
========== copied with np.ones
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
========== copied with np.full
[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]
========== copied with np.empty
[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]
