In [2]:
import numpy as np

#### **배열생성**
    * 리스트로 배열 만들기

In [3]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1)) 
print(a1.shape) # 5개의 원소 1차원 배열임을 확인
print(a1[0],a1[1],a1[2],a1[3],a1[4])

# 값 수정하기
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


<font color = "blue">***2차원형태 배열 생성***</font>

In [31]:
array_2D = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(array_2D)

print("=" * 33)

print("생성된 이차원 어레이의 구조", array_2D.shape)
print("이차원 어레이에 접근 예시 _ : array_2D[0, 0], array_2D[1][0], array_2D[2, 2] = ", array_2D[0, 0], array_2D[1][0], array_2D[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
생성된 이차원 어레이의 구조 (3, 3)
이차원 어레이에 접근 예시 _ : array_2D[0, 0], array_2D[1][0], array_2D[2, 2] =  1 4 9


---

<font color = "blue"> ***3차원 어레이 개념과 생성생성***</font>

<img src="https://kr.mathworks.com/help/matlab/math/nddemo_02_ko_KR.gif" alt="image info" />

In [32]:
# 이차원형태 배열 생성
array_3D = np.array([[ [1,2,3], [4,5,6], [7,8,9] ],
                   [ [1,2,3], [4,5,6], [7,8,9] ],
                   [ [1,2,3], [4,5,6], [7,8,9] ]])
print(array_3D)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [33]:
print(array_3D.shape)

(3, 3, 3)


<font color = "blue">***배열 생성과 초기화***</font>